apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hpecxi-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: hpecxi-dp-ds
  template:
    metadata:
      labels:
        name: hpecxi-dp-ds
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: ghcr.io/hewlettpackard/cxi-k8s-device-plugin:0.0.1-beta
        imagePullPolicy: Always
        name: hpecxi-dp-cntr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: sys
            mountPath: /sys
          - name: cray
            mountPath: /opt/cray
          - name: libfabric
            mountPath: /usr/lib64
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: cray
          hostPath:
            path: /opt/cray
        - name: libfabric
          hostPath:
            path: /usr/lib64