apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: hsn1-ipvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ipvlan",
    "master": "hsn1",
    "mode": "l2",
    "ipam": {
        "type": "whereabouts",
        "range": "10.150.11.1/28"
      }
  }'